export function internalInferencePage() {
  const nonce = crypto.randomUUID();
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Internal Spark inference</title></head><body>
<h1>Internal Spark inference</h1><p>Sign in with your approved GitHub account. Requests use DGX Spark through Outfitter beta.</p>
<button id="login">Sign in with GitHub</button><form id="form"><label>Prompt <textarea id="prompt" required maxlength="8000">Reply with a short hello.</textarea></label><button id="send">Send</button></form><pre id="result" role="status"></pre>
<script nonce="${nonce}">
const result=document.getElementById('result'),send=document.getElementById('send');
document.getElementById('login').onclick=async()=>{try{const r=await fetch('/api/auth/sign-in/social',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:'github',callbackURL:location.href})});const d=await r.json();if(r.ok&&d.url)location.assign(d.url);else result.textContent='Sign-in unavailable.';}catch{result.textContent='Sign-in unavailable.';}};
document.getElementById('form').onsubmit=async(e)=>{e.preventDefault();send.disabled=true;result.textContent='';try{const r=await fetch('/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:'spark/glm-5.3-flash',stream:true,max_tokens:512,messages:[{role:'user',content:document.getElementById('prompt').value}]})});if(!r.ok){result.textContent='Request failed ('+r.status+'). Sign in with an approved account.';return;}const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line.startsWith('data: ')||line.trim()==='data: [DONE]')continue;try{const d=JSON.parse(line.slice(6));result.textContent+=d.choices?.[0]?.delta?.content??'';}catch{}}}}catch{result.textContent+='\nRequest interrupted.';}finally{send.disabled=false;}};
</script></body></html>`, { headers: { "content-type": "text/html;charset=utf-8", "cache-control": "no-store", "content-security-policy": `default-src 'none'; script-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'`, "referrer-policy": "no-referrer", "x-content-type-options": "nosniff" } });
}
