export function agentsPage() {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Manage agents | AI Outfitter</title><style>
  :root{color-scheme:dark;--bg:#07111f;--panel:#101d2e;--line:#263a51;--text:#edf5ff;--muted:#a7b9cc;--accent:#66e3b4}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 0,#12334b,var(--bg) 40%);color:var(--text);font:16px/1.5 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:2rem 1.2rem 5rem}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:3rem}a{color:var(--accent)}h1{font-size:clamp(2.2rem,7vw,5rem);line-height:1;margin:.4rem 0}h2{margin-top:0}.lede{color:var(--muted);max-width:700px;font-size:1.15rem}.panel{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:16px;padding:1.25rem;margin-top:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:.8rem}.card{border:1px solid var(--line);border-radius:10px;padding:.8rem}.card label{display:flex;gap:.6rem}.muted,small{color:var(--muted)}button,select{font:inherit;border-radius:8px;padding:.65rem .9rem;border:1px solid var(--line);background:#16283d;color:var(--text)}button.primary{background:var(--accent);color:#052016;border:0;font-weight:700}button:disabled{opacity:.5}.actions{display:flex;gap:.6rem;flex-wrap:wrap;margin-top:1rem}pre{white-space:pre-wrap;overflow:auto;background:#07111f;padding:.8rem;border-radius:8px}.hidden{display:none}.status{min-height:1.5rem;color:var(--muted)}
  </style></head><body><main><header><a href="/">AI Outfitter</a><button id="logout" class="hidden">Sign out</button></header><p class="muted">GitHub-native agent management</p><h1>Your agents,<br>outfitted.</h1><p class="lede">Install or switch structured community profiles, skills, and prompts in repositories already managed with <code>.agents</code>. Every change is previewed first; there is no text editor.</p>
  <section id="signed-out" class="panel"><h2>Connect GitHub</h2><p>Sign in through the AI Outfitter GitHub App. You will only see installed repositories named <code>.agents</code> or containing a root <code>.agents/</code>.</p><button id="signin" class="primary">Sign in with GitHub</button></section>
  <section id="manager" class="hidden"><div class="panel"><h2>1. Choose a repository</h2><select id="repo"></select><p id="repo-meta" class="status"></p><h3>Existing managed files</h3><p class="muted">Select files only when you intend to remove them. Malformed resources remain visible and read-only until GitHub can safely return their blobs.</p><div id="existing" class="grid"></div></div><div class="panel"><h2>2. Choose community resources</h2><p class="muted">Selecting a profile updates or replaces its existing files. Workflows install their resource bundle only. GitHub Actions and workflow declarations are never added.</p><div id="catalog" class="grid"></div></div><div class="panel"><h2>3. Preview one atomic change</h2><div class="actions"><button id="preview" class="primary">Preview changes</button></div><div id="preview-output"></div><div id="apply-actions" class="actions hidden"><button id="pr" class="primary">Open pull request</button><button id="direct">Commit to default branch</button></div></div></section><p id="status" class="status"></p>
  </main><script type="module">
  const $=id=>document.getElementById(id);let boot,planToken;const workflow=new URL(location.href).searchParams.get('workflow');
  async function api(path,options){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
  async function start(){try{boot=await api('/api/agents/bootstrap');if(!boot.user)return;$('signed-out').classList.add('hidden');$('manager').classList.remove('hidden');$('logout').classList.remove('hidden');for(const r of boot.repositories)$('repo').add(new Option(r.fullName,r.fullName));await renderMeta();$('repo').onchange=renderMeta;for(const item of boot.catalog){const checked=workflow===item.id?'checked':'';const availability=item.available?'Ready':'Unavailable: '+item.missing.join(', ');$('catalog').insertAdjacentHTML('beforeend','<div class="card"><label><input type="checkbox" data-resources=\''+JSON.stringify(item.resources)+'\' '+checked+(item.available?'':' disabled')+'><span><strong>'+escapeHtml(item.title)+'</strong><br><small>'+escapeHtml(item.description||'')+'</small><br><small>'+escapeHtml(availability)+'</small></span></label></div>')}}catch(e){$('status').textContent=e.message}}
  async function renderMeta(){const r=boot.repositories.find(x=>x.fullName===$('repo').value);$('repo-meta').textContent=r?(r.managedRoot||'repository root')+' · default branch '+r.defaultBranch+(r.canPush?' · direct commit available':''):'No managed repositories found';$('direct').disabled=!r?.canPush;$('existing').innerHTML='';if(!r)return;const listing=await api('/api/agents/repositories/'+r.fullName);for(const item of listing.resources)$('existing').insertAdjacentHTML('beforeend','<label class="card"><input type="checkbox" data-delete="'+escapeHtml(item.path)+'"> Remove <code>'+escapeHtml(item.path)+'</code> <small>('+item.files+' files)</small></label>')}
  $('signin').onclick=async()=>{const data=await api('/api/auth/sign-in/social',{method:'POST',body:JSON.stringify({provider:'github',callbackURL:'/agents'})});location.href=data.url};
  $('logout').onclick=async()=>{await fetch('/api/auth/sign-out',{method:'POST',headers:{'content-type':'application/json'}});location.reload()};
  $('preview').onclick=async()=>{try{const repo=boot.repositories.find(x=>x.fullName===$('repo').value);const resources=[...document.querySelectorAll('[data-resources]:checked')].flatMap(x=>JSON.parse(x.dataset.resources));const deletes=[...document.querySelectorAll('[data-delete]:checked')].map(x=>x.dataset.delete);const result=await api('/api/agents/plans',{method:'POST',body:JSON.stringify({repository:repo.fullName,managedRoot:repo.managedRoot,resources:[...new Set(resources)],deletes})});planToken=result.token;$('preview-output').innerHTML='<p>'+result.plan.changes.length+' file change(s). Review the exact contents below.</p>'+result.plan.changes.map(c=>'<details><summary>'+c.action.toUpperCase()+' '+escapeHtml(c.path)+'</summary><pre>'+escapeHtml(c.after??'(deleted)')+'</pre></details>').join('');$('apply-actions').classList.remove('hidden')}catch(e){$('preview-output').textContent=e.message;$('apply-actions').classList.add('hidden')}};
  async function apply(mode){if(!confirm(mode==='direct'?'Commit this exact preview to the default branch?':'Create a branch and pull request with this exact preview?'))return;try{const result=await api('/api/agents/apply',{method:'POST',body:JSON.stringify({token:planToken,mode})});location.href=result.pullRequestUrl||result.commitUrl}catch(e){$('status').textContent=e.message}}
  $('pr').onclick=()=>apply('pull-request');$('direct').onclick=()=>apply('direct');function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}start();
  </script></body></html>`, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "content-security-policy": `default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'`, "referrer-policy": "same-origin", "x-content-type-options": "nosniff" } });
}
