export function agentsPage() {
  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Manage agents | AI Outfitter</title><style>
  :root{color-scheme:dark;--bg:#07111f;--panel:#101d2e;--line:#263a51;--text:#edf5ff;--muted:#a7b9cc;--accent:#66e3b4}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 0,#12334b,var(--bg) 40%);color:var(--text);font:16px/1.5 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:2rem 1.2rem 5rem}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:3rem}a{color:var(--accent)}h1{font-size:clamp(2.2rem,7vw,5rem);line-height:1;margin:.4rem 0}h2{margin-top:0}.lede{color:var(--muted);max-width:700px;font-size:1.15rem}.panel{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:16px;padding:1.25rem;margin-top:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:.8rem}.card{border:1px solid var(--line);border-radius:10px;padding:.8rem}.card label{display:flex;gap:.6rem}.muted,small{color:var(--muted)}button,select{font:inherit;border-radius:8px;padding:.65rem .9rem;border:1px solid var(--line);background:#16283d;color:var(--text)}button.primary{background:var(--accent);color:#052016;border:0;font-weight:700}button:disabled{opacity:.5}.actions{display:flex;gap:.6rem;flex-wrap:wrap;margin-top:1rem}pre{white-space:pre-wrap;overflow:auto;background:#07111f;padding:.8rem;border-radius:8px}.hidden{display:none}.status{min-height:1.5rem;color:var(--muted)}
  </style></head><body><main><header><a href="/">AI Outfitter</a><button id="logout" class="hidden">Sign out</button></header><p class="muted">GitHub-native agent management</p><h1>Your agents,<br>outfitted.</h1><p class="lede">Install or switch structured community profiles, skills, and prompts in repositories already managed with <code>.agents</code>. Every change is previewed first; there is no text editor.</p>
  <section id="signed-out" class="panel"><h2>Connect GitHub</h2><p>Sign in through the AI Outfitter GitHub App. You will only see installed repositories named <code>.agents</code> or containing a root <code>.agents/</code>.</p><button id="signin" class="primary">Sign in with GitHub</button></section>
  <section id="manager" class="hidden"><div class="panel"><h2>1. Choose a workflow</h2><p class="muted">Each package contains its canonical workflow YAML and every agent-owned dependency resolved by Outfitter at one exact community commit.</p><select id="workflow"></select><p id="workflow-meta" class="status"></p></div><div class="panel"><h2>2. Choose or create a .agents repository</h2><select id="repo"></select><p id="repo-meta" class="status"></p><div class="actions"><select id="account"></select><select id="visibility"><option value="public">Public</option><option value="private">Private</option></select><button id="create">Create .agents repository</button></div><h3>Existing managed files</h3><div id="existing" class="grid"></div></div><div class="panel"><h2>3. Preview one atomic change</h2><div class="actions"><button id="preview" class="primary">Preview changes</button></div><div id="preview-output"></div><div id="apply-actions" class="actions hidden"><button id="pr" class="primary">Open pull request</button><button id="direct">Commit to default branch</button></div></div></section><p id="status" class="status"></p>
  </main><script type="module">
  const $=id=>document.getElementById(id);let boot,planToken;const requestedWorkflow=new URL(location.href).searchParams.get('workflow');
  async function api(path,options){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
  async function start(){try{boot=await api('/api/agents/bootstrap');if(!boot.user)return;$('signed-out').classList.add('hidden');$('manager').classList.remove('hidden');$('logout').classList.remove('hidden');for(const item of boot.catalog)$('workflow').add(new Option(item.title,item.id));if(requestedWorkflow&&boot.catalog.some(x=>x.id===requestedWorkflow))$('workflow').value=requestedWorkflow;for(const r of boot.repositories)$('repo').add(new Option(r.fullName,r.fullName));for(const a of boot.accounts.filter(x=>!x.hasAgentsRepository))$('account').add(new Option(a.login+' · '+a.type,a.login));$('workflow').onchange=renderWorkflow;renderWorkflow();await renderMeta();$('repo').onchange=renderMeta}catch(e){$('status').textContent=e.message}}
  function renderWorkflow(){const item=boot.catalog.find(x=>x.id===$('workflow').value);$('workflow-meta').textContent=item?item.description+' · source '+item.sourceSha.slice(0,12):''}
  async function renderMeta(){const r=boot.repositories.find(x=>x.fullName===$('repo').value);$('repo-meta').textContent=r?(r.managedRoot||'repository root')+' · default branch '+r.defaultBranch+(r.canPush?' · direct commit available':''):'No managed repositories found';$('direct').disabled=!r?.canPush;$('existing').innerHTML='';if(!r)return;const listing=await api('/api/agents/repositories/'+r.fullName);for(const item of listing.resources)$('existing').insertAdjacentHTML('beforeend','<label class="card"><input type="checkbox" data-delete="'+escapeHtml(item.path)+'"> Remove <code>'+escapeHtml(item.path)+'</code> <small>('+item.files+' files)</small></label>')}
  $('signin').onclick=async()=>{const data=await api('/api/auth/sign-in/social',{method:'POST',body:JSON.stringify({provider:'github',callbackURL:'/agents'})});location.href=data.url};
  $('logout').onclick=async()=>{await fetch('/api/auth/sign-out',{method:'POST',headers:{'content-type':'application/json'}});location.reload()};
  $('create').onclick=async()=>{try{if(!confirm('Create '+$('account').value+'/.agents and make its initial commit?'))return;const result=await api('/api/agents/repositories',{method:'POST',body:JSON.stringify({account:$('account').value,workflow:$('workflow').value,private:$('visibility').value==='private'})});location.href=result.commitUrl}catch(e){$('status').textContent=e.message}};
  $('preview').onclick=async()=>{try{const repo=boot.repositories.find(x=>x.fullName===$('repo').value);const deletes=[...document.querySelectorAll('[data-delete]:checked')].map(x=>x.dataset.delete);const result=await api('/api/agents/plans',{method:'POST',body:JSON.stringify({repository:repo.fullName,managedRoot:repo.managedRoot,workflow:$('workflow').value,deletes})});planToken=result.token;$('preview-output').innerHTML='<p>'+result.plan.changes.length+' file change(s). Review the exact contents below.</p>'+result.plan.changes.map(c=>'<details><summary>'+c.action.toUpperCase()+' '+escapeHtml(c.path)+'</summary><pre>'+escapeHtml(c.after??'(deleted)')+'</pre></details>').join('');$('apply-actions').classList.remove('hidden')}catch(e){$('preview-output').textContent=e.message;$('apply-actions').classList.add('hidden')}};
  async function apply(mode){if(!confirm(mode==='direct'?'Commit this exact preview to the default branch?':'Create a branch and pull request with this exact preview?'))return;try{const result=await api('/api/agents/apply',{method:'POST',body:JSON.stringify({token:planToken,mode})});location.href=result.pullRequestUrl||result.commitUrl}catch(e){$('status').textContent=e.message}}
  $('pr').onclick=()=>apply('pull-request');$('direct').onclick=()=>apply('direct');function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}start();
  </script></body></html>`, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "content-security-policy": `default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'`, "referrer-policy": "same-origin", "x-content-type-options": "nosniff" } });
}

const shell = (title: string, body: string, script = "") => new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${title} | AI Outfitter</title><style>
:root{color-scheme:dark;--bg:#11110f;--panel:#1c1b18;--line:#3a3933;--text:#f3efe5;--muted:#bbb7ae;--accent:#ff8b3d}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#262019,var(--bg) 32rem);color:var(--text);font:16px/1.55 system-ui,sans-serif}main{width:min(100% - 2rem,74rem);margin:auto;padding:6rem 0}a{color:#ffb36b}.eyebrow{color:var(--accent);font:700 .75rem ui-monospace;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(2.6rem,7vw,5rem);line-height:.95;margin:.5rem 0 2rem}.lede,.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(18rem,1fr));gap:1rem}.card{padding:1.25rem;border:1px solid var(--line);background:var(--panel)}.badge{display:inline-block;padding:.25rem .5rem;border:1px solid currentColor;border-radius:999px;font:700 .7rem ui-monospace;text-transform:uppercase}.actions{display:flex;flex-wrap:wrap;gap:.7rem;margin-top:1rem}.button,button{display:inline-block;padding:.7rem .9rem;border:1px solid var(--accent);background:transparent;color:#ffb36b;font:700 .78rem system-ui;letter-spacing:.06em;text-decoration:none;text-transform:uppercase;cursor:pointer}.button.primary,button.primary{background:var(--accent);color:#211107}.counts{display:flex;gap:.8rem;color:var(--muted);font-size:.85rem}.hidden{display:none}.error{color:#ff9c8f}
</style></head><body><main>${body}</main>${script ? `<script type="module">${script}</script>` : ""}</body></html>`, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "content-security-policy": "default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'" } });
const html = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

export function organizationsPage(appSlug: string) {
  return shell("Organizations", `<p class="eyebrow">Installation health</p><h1>Your organizations</h1><p class="lede">Switch the account AI Outfitter manages, inspect each <code>.agents</code> repository, or install the GitHub App for another organization.</p><div id="accounts" class="grid"><p class="muted">Loading installations…</p></div><div class="actions"><a class="button primary" href="https://github.com/apps/${encodeURIComponent(appSlug)}/installations/new?state=organizations">Add organization</a></div><p id="error" class="error"></p>`, `
const root=document.querySelector('#accounts'),error=document.querySelector('#error');
const data=await fetch('/api/organizations'+location.search).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).catch(e=>{error.textContent=e.message;return null});
if(data){root.innerHTML='';for(const a of data.accounts){const counts=a.counts||{installed:0,outdated:0,overridden:0};const card=document.createElement('article');card.className='card';card.innerHTML='<span class="badge">'+(a.active?'Active':a.type)+'</span><h2>'+escape(a.login)+'</h2><p class="muted">'+(a.hasAgentsRepository?(a.private?'Private':'Public')+' .agents repository':'No .agents repository')+'</p><div class="counts"><span>'+counts.installed+' installed</span><span>'+counts.outdated+' outdated</span><span>'+counts.overridden+' overridden</span></div><div class="actions"><a class="button" href="/orgs/'+encodeURIComponent(a.login)+'/workflows/">Open</a><a class="button" href="https://github.com/settings/installations/'+a.installationId+'">Configure installation</a>'+(a.active?'':'<button data-login="'+escape(a.login)+'">Make active</button>')+'</div>';root.append(card)}for(const button of root.querySelectorAll('[data-login]'))button.onclick=async()=>{await fetch('/api/scope',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({login:button.dataset.login})});location.reload()}}
function escape(value){const el=document.createElement('div');el.textContent=value;return el.innerHTML}`);
}

export function organizationWorkflowsPage(login: string) {
  const encoded = encodeURIComponent(login);
  return shell(`${html(login)} workflows`, `<p class="eyebrow">Organization workflow catalog</p><h1>${html(login)}</h1><p class="lede">Status is calculated against the current embedded catalog and the repository's complete workflow closure.</p><div id="workflows" class="grid"><p class="muted">Inspecting repository…</p></div><p id="error" class="error"></p>`, `
const root=document.querySelector('#workflows'),error=document.querySelector('#error');const login=${JSON.stringify(login)};
fetch('/api/orgs/${encoded}/workflows').then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json()}).then(data=>{root.innerHTML='';for(const item of data.workflows){const card=document.createElement('article');card.className='card';const action=item.action==='none'?(item.state==='overridden'?'<span class="muted">Inspect changes — coming soon</span>':''):'<a class="button primary" href="/orgs/${encoded}/install?workflow='+encodeURIComponent(item.id)+'">'+item.action+'</a>';card.innerHTML='<span class="badge">'+item.state+'</span><h2>'+escape(item.title||item.id)+'</h2><p class="muted">'+escape(item.reason||item.description||'')+'</p><div class="actions">'+action+'<a class="button" href="'+data.repositoryUrl+'">GitHub repository</a></div>';root.append(card)}}).catch(e=>{error.textContent=e.message});function escape(value){const el=document.createElement('div');el.textContent=value;return el.innerHTML}`);
}
